package com.portfolio.salesmanager.util;

public enum Permission {
    READ_ALL_USERS,
    SAVE_ONE_USER,
    UPDATE_ONE_USER,
    DELETE_ONE_USER,

    READ_ALL_PRODUCTS,
    SAVE_ONE_PRODUCT,
    UPDATE_ONE_PRODUCT,
    DELETE_ONE_PRODUCT,

    READ_ALL_CATEGORIES,
    SAVE_ONE_CATEGORY,
    UPDATE_ONE_CATEGORY,
    DELETE_ONE_CATEGORY,

    READ_ALL_BRANCHES,
    SAVE_ONE_BRANCH,
    UPDATE_ONE_BRANCH,
    DELETE_ONE_BRANCH,

    READ_INVENTORY,
    READ_BRANCH_INVENTORY,
    SAVE_INVENTORY,
    UPDATE_INVENTORY,
    DELETE_INVENTORY,

    CREATE_ONE_SALE,
    READ_ALL_SALES,
    READ_USER_SALES,
    READ_ANY_BRANCH_SALES,
    READ_BRANCH_SALES,
    READ_MY_SALES,
    CANCEL_ONE_SALE;
}
